### ISSUE TITLE
Invalid expression in s:load?

### ISSUE THREAD

**Issue by bearcatsandor** [romgrk/nvim#1]
I really like the modular aspects of your config, and i'm trying ti duplicate it. Right off the bat i'm getting an error.

```
Error detected while processing function <SNR>2_load:
line    1:
E117: Unknown function: path#Join
E15: Invalid expression: a:file[0] == '/' ? a:file : path#Join([$vim, a:file])
line    2:
E121: Undefined variable: file
E116: Invalid arguments for function fnameescape
line    1:
E117: Unknown function: path#Join
E15: Invalid expression: a:file[0] == '/' ? a:file : path#Join([$vim, a:file])
line    2:
E121: Undefined variable: file
```

I'm on nvim 0.4.4. Isn't path a built in, or do you have an include file somewhere that i'm missing?

Thanks.

**Comment by romgrk** [comment]
vim-maktaba's source from a few years ago is [included](https://github.com/romgrk/nvim/blob/master/autoload/path.vim) in my config. You can probably replace those by `join([...], '/')`, it should work even on windows.

**Comment by bearcatsandor** [comment]
I got it working! Thank you.
