### ISSUE TITLE
I'm trying to use your configuration...

### ISSUE THREAD

**Issue by Zachary-Lee-Jaeho** [romgrk/nvim#2]
After I cloned your repo, and hit the command `nvim --headless +PlugInstall +PlugUpdate`, some error message is emitted.

> nvim --headless +PlugInstall +PlugUpdate                                                                                                                    
> 
> Error detected while processing function <SNR>1_load:
> line    2:
> E5113: Error while calling lua chunk: /home/zachary/.config/nvim/rc/plugins/barbar.lua:5: attempt to index field 'g' (a nil value)
> E5113: Error while calling lua chunk: /home/zachary/.config/nvim/rc/plugins/beacon.lua:7: attempt to index field 'g' (a nil value)
> E5113: Error while calling lua chunk: /home/zachary/.config/nvim/rc/plugins/dap.after.lua:1: module 'dap' not found:
> 	no field package.preload['dap']
> 	no file '/home/zachary/.config/nvim/lua/dap.lua'
> 	no file '/home/zachary/.config/nvim/lua/dap/init.lua'
> 	no file '/home/zachary/.config/nvim/bundle/sideways.vim/lua/dap.lua'
> 	no file '/home/zachary/.config/nvim/bundle/sideways.vim/lua/dap/init.lua'
> 	no file '/home/zachary/.config/nvim/bundle/splitjoin.vim/lua/dap.lua'
> 	no file '/home/zachary/.config/nvim/bundle/splitjoin.vim/lua/dap/init.lua'
> 	no file '/home/zachary/.config/nvim/bundle/CamelCaseMotion/lua/dap.lua'
> 	no file '/home/zachary/.config/nvim/bundle/CamelCaseMotion/lua/dap/init.lua'
> 	no file '/home/zachary/.config/nvim/bundle/textobj-word-column.vim/lua/dap.lua'
> 	no file '/home/zachary/.config/nvim/bundle/textobj-word-column.vim/lua/dap/init.lua' 

what is the problem??

**Comment by romgrk** [comment]
Make sure that you're running a nightly version of neovim.
